picture_party_site/image/urls.py
from django.urls import path

from . import views

app_name = "image"
urlpatterns = [
    # /image/add/1
    path("add/<int:party_id>", views.add_image, name="add_image"),
]

picture_party_site/party/urls.py
from django.urls import path

from . import views

app_name = "party"
urlpatterns = [
    # /party/
    path("", views.index, name="index"),
    # /party/add/
    path("add/", views.add_party, name="add_party"),
    # /party/5/
    path("<int:party_id>/", views.detail, name="detail"),
]

picture_party_site/picture_party_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("party/", include("party.urls")),
    path("image/", include("image.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picture_party_site/image/models.py
from django.db import models


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "party_{0}/{1}".format(instance.party_id, filename)


class Image(models.Model):
    party_id = models.ForeignKey("party.Party", on_delete=models.CASCADE,)
    image = models.ImageField(upload_to=user_directory_path)

picture_party_site/party/models.py
from django.db import models
from datetime import datetime


class Party(models.Model):
    party_name = models.CharField(max_length=24)
    created_at = models.DateTimeField("date published", default=datetime.now())

    def has_expired(self):
        return self.created_at < timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return f"{self.id} {self.party_name}"

picture_party_site/image/forms.py
from django import forms


class ImageForm(forms.Form):
    image = forms.ImageField(label="Image to add")

picture_party_site/party/forms.py
from django import forms


class PartyForm(forms.Form):
    party_name = forms.CharField(label="Party Name", max_length=24)

picture_party_site/image/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.apps import apps

from .models import Image
from .forms import ImageForm

Party = apps.get_model("party", "Party")


def add_image(request, party_id):
    party = get_object_or_404(Party, pk=party_id)

    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)

        if form.is_valid():

            # insert a new Image into the db
            image_data = {**form.cleaned_data}
            image_data["party_id"] = party

            image = Image(**image_data)
            image.save()

            return redirect("party:detail", party_id=party.id)
        return HttpResponse(f"Something went wrong...")
    else:
        form = ImageForm()

    return render(request, "image/add.html", {"party": party, "imageForm": form})

picture_party_site/party/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.apps import apps

from .models import Party
from .forms import PartyForm

Image = apps.get_model("image", "Image")


def index(request):
    latest_party_list = Party.objects.order_by("created_at")
    context = {"latest_party_list": latest_party_list}
    return render(request, "party/index.html", context)


def detail(request, party_id):
    party = get_object_or_404(Party, pk=party_id)
    images = Image.objects.filter(party_id=party_id)
    return render(request, "party/detail.html", {"party": party, "images": images})


def add_party(request):
    if request.method == "POST":

        form = PartyForm(request.POST)
        if form.is_valid():

            # insert a new Party into the db
            party = Party(**form.cleaned_data)
            party.save()

            return redirect("party:detail", party_id=party.id)
    else:
        form = PartyForm()

    return render(request, "party/add.html", {"partyForm": form})

picture_party_site/picture/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.apps import apps

from .models import Picture
from .forms import PictureForm

Party = apps.get_model('party', 'Party')

def add_picture(request, party_id):
    party = get_object_or_404(Party, pk=party_id)

    if request.method == "POST":
        form = PictureForm(request.POST, request.FILES)

        if form.is_valid():

            # insert a new Picture into the db
            picture_data = {**form.cleaned_data}
            picture_data["party_id"] = party

            picture = Picture(**picture_data)
            picture.save()

            return HttpResponse(f"You successfully added a picture to {party.party_name}")
        return HttpResponse(f"Something went wrong...")
    else:
        form = PictureForm()

    return render(request, "picture/add.html", {"party": party, "pictureForm": form})

picture_party_site/image/templates/image/add.html
{% block title %}Adding to party: {{ party.party_name }}{% endblock %}

<form enctype="multipart/form-data"
      action="{% url 'image:add_image' party.id %}"
      method="post">
    {% csrf_token %}
    {{ imageForm }}
    <input type="submit" value="Submit">
</form>

picture_party_site/party/templates/party/add.html
<form action="{% url 'party:add_party' %}" method="post">
    {% csrf_token %}
    {{ partyForm }}
    <input type="submit" value="Submit">
</form>

picture_party_site/party/templates/party/detail.html
{% load static %}

{{ party }}

<br/>

<a href="{% url 'image:add_image' party.id %}">Add an image to {{ party.party_name }}</a>

<br/>

{% for image in images %}
  <img src="{{ image.image.url }}" alt="Not available.">
  <br/>
{% endfor %}

picture_party_site/party/templates/party/index.html
{% if latest_party_list %}
    <ul>
    {% for party in latest_party_list %}
      <li><a href="{% url 'party:detail' party.id %}">{{ party.party_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No parties are available.</p>
{% endif %}

picture_party_site/picture/templates/picture/add.html
{% block title %}Adding to party: {{ party.party_name }}{% endblock %}

<form enctype="multipart/form-data"
      action="{% url 'picture:add_picture' party.id %}"
      method="post">
    {% csrf_token %}
    {{ pictureForm }}
    <input type="submit" value="Submit">
</form>